spring:
  application:
    name: TacoCloud
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taco_cloud
    username: postgres
    password: 27112004
#  sql:
#    init:
#      mode: always